### ISSUE TITLE
spacemacs related - not working on evil-hybrid/normal-state change

### ISSUE THREAD

**Issue by et2010** [cute-jumper/fcitx.el#12]
Thank you for this amazing repo! fcitx.el is really a life-saver, with it I can use my favorite input method with evil instead of those far more inferior emacs counterparts. But the tradeoff is: it doesn't work on spacemacs hybrid state. Currently, My work around is to fork this repo and search-replace every `insert-state` with `hybrid-state`. It's ugly but that's all I can do right now since I'm not skilled in emacs lisp. So I'm wondering if this feature will be added in the future considering the fast growing spacemacs users? Thanks!

**Comment by cute-jumper** [comment]
So I'm adding a new variable `fcitx-active-evil-states`. This variable contains all the evil states in which we should activate fcitx. The default value is `'(insert emacs)`.

If you want `evil-hybrid-state` to be one of them, use the following code in your init file:

    (setq fcitx-active-evil-states '(insert emacs hybrid))

I would update the documentation later. Please report issues here if you find any problems! Thank you!

**Comment by et2010** [comment]
I'll try it when melpa updates the package, and I'll post the result here. Thanks for your fast reply!

**Comment by et2010** [comment]
It works! But I found a weird thing: when I hit <kbd>C-s</kbd> in hybrid state to enter search pattern in the mini buffer, the fcitx im is not disabled even with aggressive setup. It's not a big issue since I can always hit <kbd>Enter</kbd> to enter the word, but it feels a bit a clumsy. 

The same thing happens when I hit <kbd>C-h k</kbd> to interactively call `describe-key` (I already added <kbd>C-h</kbd> to fcitx prefix key). Even worse, when I quit the popup buffer of describe-key, the fcitx im is gone and I have to re-enable it.

**Comment by et2010** [comment]
I figured that maybe the <kbd>C-s</kbd> behavior is intended? Wow, that's cool since I never thought that we could search chinese char like this. I used to use pinyin-search package. I feel really dumb now.

**Comment by cute-jumper** [comment]
These two features don't exist in the current version.

I have thought about adding isearch support but it seems to me that if you've enabled fcitx in the current buffer, most of the buffer content should be Chinese characters and it is normal that you want to search the Chinese characters. So I leave it unimplemented. It is OK to add the support:-)

<kbd>C-h k</kbd> is a little bit different. It looks like these functions, `read-char`, `read-key`, `read-key-sequence` and etc., do not set up the minibuffer the same way as `read-string`. Adding advice to these functions should solve the problem.

I'll update the code a little bit later.

**Comment by et2010** [comment]
Yes, current implementation of <kbd>C-s</kbd> rocks! Goodbye, pinyin-search!

**Comment by cute-jumper** [comment]
I'm going to add these features in case someone finds them useful, but the isearch feature would not be enabled in the pre-defined setup functions. Note that I haven't done anything to <kbd>C-s</kbd>. It is the default behavior you can get even without this package.

**Comment by et2010** [comment]
Thank you @cute-jumper. That should solve my problems.

**Comment by cute-jumper** [comment]
These two features are now added. I-search support is not enabled in either `fcitx-default-setup` or `fcitx-aggressive-setup`, but the support for `read-*` functions will be turned on in these two setup functions.  <kbd>C-h k</kbd> should now work fine, and `ace-pinyin` now works seamlessly together with `fcitx.el` if you use `avy` as the jumping method. You don't have to disable fcitx before you use `ace-pinyin`.

**Comment by et2010** [comment]
Something went wrong, <kbd> C-h k </kbd> still not working. I'm using the aggressive setup. Here is my system spec:

- Archlinux 64 bit
- emacs 24.5.1
- spacemacs 0.105.9

fcitx:

- community/fcitx 4.2.9.1-1 (fcitx-im)
- community/fcitx-configtool 0.4.8-1
- community/fcitx-gtk2 4.2.9.1-1 (fcitx-im)
- community/fcitx-gtk3 4.2.9.1-1 (fcitx-im)
- community/fcitx-qt4 4.2.9.1-1 (fcitx-im)
- community/fcitx-qt5 1.0.5-1 (fcitx-im)
- community/fcitx-rime 0.3.1-2
- local/fcitx-sogoupinyin 2.0.0.0068-1

**Comment by cute-jumper** [comment]
I see. There is a race condition between the newly added `read-*` functions and the prefix key polling function.  I haven't figured out a good way to solve it. I'll leave this issue open.

**Comment by cute-jumper** [comment]
Just to let you know, the `read-*` functions support has been removed from the setup function. You have to manually enable it if you need. There are some issues with it on OS X(See #14 ). But if you're using Linux, you can enable this and remember to set `fcitx-use-dbus` to be `t`.

**Comment by et2010** [comment]
Thanks for the heads-up.

**Comment by colin4124** [comment]
Hi, @cute-jumper 

I am spacemacs user, I add the `(fcitx-aggressive-setup)` to user-config section, but it not work. I must M-x fcitx-aggressive-setup so the `(setq fcitx-active-evil-states '(insert emacs hybrid))` works.

**Comment by cute-jumper** [comment]
Can you give steps to reproduce the problem? There is no difference between `(fcitx-aggressive-setup)` in Elisp and `M-x fcitx-aggressive-setup`.

**Comment by colin4124** [comment]
Indeed  `(fcitx-aggressive-setup) ` in  `dotspacemacs/user-config ()` is the same as `M-x fcitx-aggressive-setup`. But the face that does not work for me.

I use spacemacs, and use `chinese` layer and set that:

> (chinese :variables
             chinese-enable-fcitx t
              chinese-enable-youdao-dict t)

Is there relative to chinese layer? If you do that and it still works,  can I send my `.spacemacs` to your email and you test whether reproduce the problem?

**Comment by cute-jumper** [comment]
@colin4124 Sorry. It seems that's my fault. You need to put `(setq fcitx-active-evil-states '(insert emacs hybrid))` before `fcitx-aggressive-setup`. That should fix the problem.

**Comment by colin4124** [comment]
@cute-jumper it works, thx very much!  ^_^

If I set as below:
> (setq fcitx-active-evil-states '(insert emacs hybrid))
>   (fcitx-prefix-keys-add "M-m") ; M-m is common in Spacemacs
>   (setq fcitx-use-dbus t) ; uncomment if you're using Linux

`(fcitx-aggressive-setup)` should after '(setq fcitx-active-evil-states '(insert emacs hybrid))' or '(setq fcitx-use-dbus t)' ?

**Comment by cute-jumper** [comment]
As long as `(fcitx-aggressive-setup)` is after `(setq fcitx-active-evil-states '(insert emacs hybrid))`, you'll be fine.

**Comment by colin4124** [comment]
ok, thx

**Comment by cute-jumper** [comment]
Hi, @et2010 

I'm closing this issue and making a new separate issue for <kbd>C-h k</kbd>. The original problem that `fcitx.el` is not working on evil-hybrid/normal-state change has already been solved and I think it is better to keep the discussion of the unsolved <kbd>C-h k</kbd> problem in a separate issue and people would not be annoyed by unrelated messages.
